name: zipf
description: Dart implementation of a Zipf-distributed random number generator.
version: 0.0.1
repository: https://github.com/brokeyourbike/dart_zipf/
issue_tracker: https://github.com/brokeyourbike/dart_zipf/issues
homepage: https://github.com/brokeyourbike/dart_zipf

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.8

dev_dependencies:
  coverage: ^0.14.1
  mockito: ^4.1.1
  pedantic: ^1.9.0
  rxdart: ^0.24.0
  test: ^1.14.6